[Language]
Type=2052

#搜索默认网络配置
[SEARCHCONFIG]
<<<<<<< .mine
Address=010.168.001.222
||||||| .r631
Address=169.254.001.222
=======
Address=192.168.000.222
>>>>>>> .r652
Port=6012:LSGate
Baud=38400
Frame=8E1

#读卡器默认端口
[READERPORT]
Port=9909

#会议签到门默认端口
[MEETINGGATEPORT]
Port=6012

#安全门默认端口
[LSGATEPORT]
Port=6012

[RPANPORT]
Port=4800

[RL8000PORT]
Port=9900

#默认通信方式
[Communications]
<<<<<<< .mine
Type=串口通信
||||||| .r631
Type=串口通信
=======
Type=网络通信
>>>>>>> .r652

#读卡参数
[ReadCardPara]
IsReadNew=0
IsAFI=0
AFI Value=0x00
IsISO1443A=1
IsISO15693=1
GridMode=2
IsPlayVoice=0
IsNoticeRecordChange=1
RecordChangeNum=1
IsClearRecord=1
IsActNewTag=0
ActMode=1
IsFiltrationTag=1
IsISO18000p3m3=1
IsDealWithUnfinish=1
bOutputProtocal=1
bShowInventoryTime=1
bResetAntennas =0
bCloseRF=0

[NoiseDetect]
MaxValueCoordinate=[500,4000]
AvgValueCoordinate=[0,8000]
IsShowMaxCoordinate=1
IsShowAvgCoordinate=1
AlarmValue=1200
IsSaveAlarmPoint=0
IsSaveAllPoint=0
TimeCoordinateVal=100
MonitorObj=0
